channels:
- conda-forge
dependencies:
- python=3.12.10
- pip<=25.0.1
- pip:
  - mlflow==3.1.1
  - cloudpickle==3.1.1
  - numpy==2.1.1
  - pandas==2.2.2
  - psutil==7.0.0
  - scikit-learn==1.5.2
  - scipy==1.14.1
name: mlflow-env
